project:
  type: website

website:
  title: "TLong"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - data_analysis.qmd

format:
  html:
    theme: 
      light: zephyr
      dark: vapor
    css: styles.css
    toc: true

editor: visual

execute: 
  freeze: auto
